### ISSUE TITLE
OpenAI Integration is not working with @pezzo/integrations

### ISSUE THREAD

**Issue by GalDayan** [pezzolabs/pezzo#29]
# Pezzo console
<img width="604" alt="image" src="https://github.com/pezzolabs/pezzo/assets/24251369/95c85c68-e077-4d0d-92dd-f9e5fac21441">

# Actual usage
<img width="651" alt="image" src="https://github.com/pezzolabs/pezzo/assets/24251369/13fb82ba-67f0-40d5-b015-f00eb7cf6a8f">

<img width="523" alt="image" src="https://github.com/pezzolabs/pezzo/assets/24251369/f9124348-74c2-4870-b676-abdedc7aec15">

**Comment by arielweinberger** [comment]
Thanks for reporting! This has been fixed as of `v0.0.15-alpha` of the NPM packages.

With regards to the import path, you're getting this error because we use the [NPM exports feature](https://www.npmjs.com/package/exports) in package.json.

The thing is, for this to work properly using TypeScript, you'll have to set `compilerOptions.moduleResolutions` to `nodenext` or `node16`.

We understand this is not ideal as some projects cannot make the switch, and we generally want it to be easy to integrate, so we're going to look into an alternative way of exposing the module.

Closing this for now.
