### ISSUE TITLE
Prompt schema management and validation

### ISSUE THREAD

**Issue by VinnyChase28** [pezzolabs/pezzo#96]
### Proposal

A tab for prompts that shows the schema/types that the prompt should return, and is editable.

### Use-Case

this makes it so you dont have to do any custom code or prompting this yourself, and makes it easy to add changes to what we are passing the prompt / getting back. 

Bonus if we can make it typesafe in typescript such that if we are not passing the right things in pezzo client it shows a type  error 

### Is this a feature you are interested in implementing yourself?

yes

**Comment by arielweinberger** [comment]
Thanks for creating the feature request. I think this is an essential feature for delivering Gen. AI changes reliably. Sort of like schema management for Kafka. Pezzo could then validate that the response corresponds to the schema.

About the bonus point - this will likely be impossible at this point in time, due to how TypeScript works. If the schemas were static, we could've figured something out at build time (taking `zod` as an example). However, Pezzo's nature is that you can iterate and adjust AI prompts on the fly without rebuilding and redeploying, so this will most likely be out of scope for now.

I'll add to that and say that you can currently execute prompts and provide a generic while doing so, to ensure type safety when receiving the response.

```ts
await openai.run<YourType>("PromptName", options);
```

**Comment by arielweinberger** [comment]
Closing this for now. We have great plans in the future for application-level schema validation (potentially with CI/CD integrations).
